name: Releases

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GETDOLAR_TOKEN }}
        goos: linux
        goarch: amd64
        binary_name: "getdolar"
        build_command: make build
